### ISSUE TITLE
Proxifier Checksum

### ISSUE THREAD

**Issue by Zamanry** [ye4241/chocolatey-packages#2]
Hello, I am trying to download Proxifier, but keep getting a checksum error. I can download other packages without issue. I've resulted in downloading straight from proxifier.com instead. See the error below:
![image](https://user-images.githubusercontent.com/28152647/161572943-381ab428-9940-40c3-9164-6b8edfa9a542.png)

*Note: If this is not the right location to make this issue, let me know where to go. I couldn't find a better place on the Proxifier choco page.*

**Comment by ye4241** [comment]
I will try to check the hashes again. For this time, please add --ignore-checksums to the choco install command. such as, 
`choco install proxifier  --ignore-checksums`

**Comment by ye4241** [comment]
Hashes is changed, and there is some update of the website of https://www.proxifier.com, I will fix this issue later. Thanks for your report.

**Comment by ye4241** [comment]
Fixed, and just pushed 4.07 to choco packages.
